# Generated by Django 3.2.4 on 2021-07-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
